### ISSUE TITLE
Weird Symbol Generation

### ISSUE THREAD

**Issue by gluax** [ConnorGray/clap-markdown#13]
Some weird symbols are generated when running over my CLI with the latest version. 

The characters `Γå┤`seems to be in place of `↴`.

![image](https://user-images.githubusercontent.com/16431709/213540979-ccac422f-7142-49dd-b5fe-c5063bf639c8.png)

The characters `ΓÇö` seems to be in place of `— `.

![image](https://user-images.githubusercontent.com/16431709/213541227-5618d77d-3adc-49bc-b72a-c805ae3a1ea3.png)

So that you know, I'm running this on Windows. 

**EDIT**: I forgot to mention I'm using the `print_help_markdown` method.

**Comment by ConnorGray** [comment]
Just a hunch, but this looks like it might be an encoding issue.

`clap-markdown` generates UTF-8 encoded output.

From the screenshots it looks like you're using Visual Studio Code. If you look in the bottom right corner of the window, do you see the status indicator that shows the encoding? For example, here is what I see on my computer:

![Screen Shot 2023-01-19 at 1 58 16 PM](https://user-images.githubusercontent.com/5759631/213546879-cf044794-5c8c-4299-a0dd-803564bcab3e.png)

Which shows I'm viewing the file using UTF-8. What encoding is present there on your computer?

**Comment by gluax** [comment]
I can confirm that piping it from Windows Powershell changed the encoding. The default encoding for piping in Powershell is `UTF-16 LE`.  I'll have it written directly to the file to avoid this problem. Thanks for the help!

**Comment by ConnorGray** [comment]
You're welcome! Let me know if you run into any further issues, or have any feedback or suggestions.
