### ISSUE TITLE
Items hidden in help are shown in markdown generation

### ISSUE THREAD

**Issue by leighmcculloch** [ConnorGray/clap-markdown#18]
It's possible to hide options in the clap help output with the `#[arg(..., hide)]` attribute. The attribute hides the flag/option in the help output. 

`clap-markdown` still includes hidden options though, making it's output inconsistent with the clap help output.

**Comment by ilyagr** [comment]
https://github.com/ConnorGray/clap-markdown/pull/15 claims to fix this. I haven't looked at it carefully, but I think these should be linked.
